version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lifelines_postgres
    environment:
      POSTGRES_DB: lifelines_db
      POSTGRES_USER: lifelines_user
      POSTGRES_PASSWORD: lifelines_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: